server:
  port: ${PORT:8080}

spring:
  application:
    name: contact-service

  datasource:
    url: "jdbc:postgresql://ep-lingering-wind-a1avid0n-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE:true}
            required: ${MAIL_STARTTLS_REQUIRED:true}
          ssl:
            enable: ${MAIL_SSL_ENABLE:false}
          trust: smtp.gmail.com
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
        debug: ${MAIL_DEBUG:false}
    default-encoding: UTF-8
contact:
  owner:
    email: ${MAIL_USERNAME}