server:
  port: ${PORT:8080}

spring:
  application:
    name: contact-service

  datasource:
    url: jdbc:postgresql://ep-lingering-wind-a1avid0n-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true